export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_NO_RESULTS = 'SET_NO_RESULTS';
export const SET_TRENDING_MOVIES = 'SET_TRENDING_MOVIES';
export const SET_TRENDING_TV_SHOWS = 'SET_TRENDING_TV_SHOWS';
export const SET_GENRES = 'SET_GENRES';
export const SET_SELECTED_GENRE = 'SET_SELECTED_GENRE';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

export const SET_MOVIE_DETAILS = 'SET_MOVIE_DETAILS';
export const SET_MOVIE_CREDITS = 'SET_MOVIE_CREDITS';
